site_name: code sharing
site_url: https://dvddmg.github.io/code_sharing/
repo_url: https://github.com/dvddmg/code_sharing
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
